language: cpp
os: linux
dist: xenial

matrix:
  include:
    - env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9 && CCC=g++-9"
      os: linux
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - doxygen
            - graphviz
      compiler: gcc

    - env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10 && CCC=g++-10"
      os: linux
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - doxygen
            - graphviz
      compiler: gcc

before_install:
    - eval "${MATRIX_EVAL}"

script: make cccc && make docs && make test

install: true

sudo: false

notifications:
  irc: "chat.freenode.net#code-hell"
