matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - doxygen
            - graphviz
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && CCC=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - doxygen
            - graphviz
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CCC=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script: make cccc && make docs && make test

install: true

sudo: false

notifications:
  irc: "chat.freenode.net#code-hell"
